version: '3.3'

volumes:
  spordieta_storage_vol:
  spordieta_postgres_vol:

services:

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: spordieta_postgres
    volumes:
      - spordieta_postgres_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=spordieta

  storage:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile.storage
    container_name: spordieta_storage
    ports:
     - 8081:8081
    volumes:
      - spordieta_storage_vol:/data
    environment:
      - STORAGE_PORT=8081
      - STORAGE_ROOT_DIR=/data

  core:
    depends_on:
      - postgres
      - storage
    build:
      context: ./
      dockerfile: Dockerfile.core
    container_name: spordieta_core
    ports:
     - 8080:8080
    environment:
      - CORE_PORT=8080
      - STORAGE_HOSTNAME=storage
      - STORAGE_PORT=8081
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=spordieta
